version: '3.1'

services:
  mysql:
    image: mariadb:latest
    volumes:
     - db_data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8181:80
    volumes:
     - /sessions
    depends_on:
     - mysql
  web:
    depends_on:
     - mysql
    image: wordpress:latest
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=root
    ports:
     - "8080:80"
    volumes:
     - ./:/var/www/html/
     - ./wp-content/:/var/www/html/wp-content
volumes:
  db_data: