version: '3.1'

services:

  wordpress:
    image: wordpress:6.1.1-php8.0-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dev
      WORDPRESS_DB_PASSWORD: dev
      WORDPRESS_DB_NAME: ebwp.demo
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ebwp.demo
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8181:80
    volumes:
      - /sessions
    depends_on:
      - db

volumes:
  db:
